databaseChangeLog = {

	changeSet(author: "parker", id: "1308145138453-1") {

		sql("""
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'afg', 'Afghanistan', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'alb', 'Albania', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'dza', 'Algeria', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'asm', 'American Samoa', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'and', 'Andorra', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'ago', 'Angola', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'aia', 'Anguilla', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'ata', 'Antarctica', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'atg', 'Antigua and Barbuda', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'arg', 'Argentina', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'arm', 'Armenia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'abw', 'Aruba', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'aus', 'Australia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'aut', 'Austria', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'aze', 'Azerbaijan', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'bhs', 'Bahamas', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'bhr', 'Bahrain', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'bgd', 'Bangladesh', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'brb', 'Barbados', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'blr', 'Belarus', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'bel', 'Belgium', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'blz', 'Belize', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'ben', 'Benin', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'bmu', 'Bermuda', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'btn', 'Bhutan', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'bol', 'Bolivia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'bih', 'Bosnia and Herzegovina', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'bwa', 'Botswana', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'bvt', 'Bouvet Island', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'bra', 'Brazil', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'iot', 'British Indian Ocean Territory', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'vgb', 'British Virgin Islands', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'brn', 'Brunei Darussalam', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'bgr', 'Bulgaria', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'bfa', 'Burkina Faso', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'bdi', 'Burundi', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'khm', 'Cambodia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'cmr', 'Cameroon', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'can', 'Canada', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'cpv', 'Cape Verde', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'cym', 'Cayman Islands', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'caf', 'Central African', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'tcd', 'Chad', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'chl', 'Chile', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'chn', 'China', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'cxr', 'Christmas Island', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'cck', 'Cocos (Keeling) Islands', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'col', 'Colombia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'com', 'Comoros', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'cok', 'Cook Islands', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'cri', 'Costa Rica', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'hrv', 'Croatia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'cub', 'Cuba', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'cyp', 'Cyprus', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'cze', 'Czech Republic', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'civ', 'Côte d''Ivoire', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'prk', 'Democratic People''s Republic of Korea', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'dnk', 'Denmark', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'dji', 'Djibouti', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'dma', 'Dominica', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'dom', 'Dominican Republic', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'ecu', 'Ecuador', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'egy', 'Egypt', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'slv', 'El Salvador', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'gnq', 'Equatorial Guinea', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'eri', 'Eritrea', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'est', 'Estonia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'eth', 'Ethiopia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'flk', 'Falkland Islands', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'fro', 'Faroe Islands', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'fsm', 'Federated States of Micronesia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'fji', 'Fiji', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'fin', 'Finland', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'fra', 'France', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'guf', 'French Guiana', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'pyf', 'French Polynesia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'atf', 'French Southern Territories', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'gab', 'Gabon', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'gmb', 'Gambia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'geo', 'Georgia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'deu', 'Germany', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'gha', 'Ghana', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'gib', 'Gibraltar', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'grc', 'Greece', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'grl', 'Greenland', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'grd', 'Grenada', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'glp', 'Guadeloupe', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'gum', 'Guam', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'gtm', 'Guatemala', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'gin', 'Guinea', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'gnb', 'Guinea-Bissau', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'guy', 'Guyana', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'hti', 'Haiti', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'hmd', 'Heard Island and McDonald Islands', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'hnd', 'Honduras', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'hkg', 'Hong Kong', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'hun', 'Hungary', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'isl', 'Iceland', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'ind', 'India', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'idn', 'Indonesia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'irq', 'Iraq', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'irl', 'Ireland', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'irn', 'Islamic Republic of Iran', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'imn', 'Isle of Man', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'isr', 'Israel', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'ita', 'Italy', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'jam', 'Jamaica', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'jpn', 'Japan', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'jor', 'Jordan', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'kaz', 'Kazakhstan', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'ken', 'Kenya', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'kir', 'Kiribati', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'kwt', 'Kuwait', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'kgz', 'Kyrgyzstan', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'lao', 'Lao People''s Democratic Republic', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'lva', 'Latvia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'lbn', 'Lebanon', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'lso', 'Lesotho', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'lbr', 'Liberia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'lby', 'Libyan Arab Jamahiriya', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'lie', 'Liechtenstein', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'ltu', 'Lithuania', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'lux', 'Luxembourg', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'mac', 'Macao', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'mdg', 'Madagascar', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'mwi', 'Malawi', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'mys', 'Malaysia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'mdv', 'Maldives', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'mli', 'Mali', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'mlt', 'Malta', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'mhl', 'Marshall Islands', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'mtq', 'Martinique', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'mrt', 'Mauritania', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'mus', 'Mauritius', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'myt', 'Mayotte', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'mex', 'Mexico', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'mco', 'Monaco', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'mng', 'Mongolia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'msr', 'Montserrat', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'mar', 'Morocco', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'moz', 'Mozambique', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'mmr', 'Myanmar', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'nam', 'Namibia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'nru', 'Nauru', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'npl', 'Nepal', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'nld', 'Netherlands', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'ant', 'Netherlands Antilles', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'ncl', 'New Caledonia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'nzl', 'New Zealand', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'nic', 'Nicaragua', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'ner', 'Niger', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'nga', 'Nigeria', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'niu', 'Niue', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'nfk', 'Norfolk Island', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'mnp', 'Northern Mariana Islands', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'nor', 'Norway', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'pse', 'Occupied Palestinian Territory', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'omn', 'Oman', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'pak', 'Pakistan', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'plw', 'Palau', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'pan', 'Panama', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'png', 'Papua New Guinea', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'pry', 'Paraguay', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'per', 'Peru', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'phl', 'Philippines', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'pcn', 'Pitcairn', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'pol', 'Poland', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'prt', 'Portugal', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'pri', 'Puerto Rico', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'qat', 'Qatar', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'kor', 'Republic of Korea', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'mda', 'Republic of Moldova', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'cog', 'Republic of the Congo', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'rou', 'Romania', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'rus', 'Russian Federation', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'rwa', 'Rwanda', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'reu', 'Réunion', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'shn', 'Saint Helena', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'kna', 'Saint Kitts and Nevis', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'lca', 'Saint Lucia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'vct', 'Saint Vincent and the Grenadines', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'spm', 'Saint-Pierre and Miquelon', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'wsm', 'Samoa', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'smr', 'San Marino', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'stp', 'Sao Tome and Principe', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'sau', 'Saudi Arabia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'sen', 'Senegal', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'scg', 'Serbia and Montenegro', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'syc', 'Seychelles', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'sle', 'Sierra Leone', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'sgp', 'Singapore', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'svk', 'Slovakia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'svn', 'Slovenia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'slb', 'Solomon Islands', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'som', 'Somalia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'zaf', 'South Africa', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'sgs', 'South Georgia and the South Sandwich Islands', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'esp', 'Spain', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'lka', 'Sri Lanka', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'sdn', 'Sudan', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'sur', 'Suriname', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'sjm', 'Svalbard and Jan Mayen', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'swz', 'Swaziland', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'swe', 'Sweden', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'che', 'Switzerland', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'syr', 'Syrian Arab Republic', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'twn', 'Taiwan', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'tjk', 'Tajikistan', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'tha', 'Thailand', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'cod', 'The Democratic Republic Of The Congo', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'mkd', 'The Former Yugoslav Republic of Macedonia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'tls', 'Timor-Leste', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'tgo', 'Togo', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'tkl', 'Tokelau', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'ton', 'Tonga', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'tto', 'Trinidad and Tobago', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'tun', 'Tunisia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'tur', 'Turkey', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'tkm', 'Turkmenistan', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'tca', 'Turks and Caicos Islands', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'tuv', 'Tuvalu', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'vir', 'U.S. Virgin Islands', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'uga', 'Uganda', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'ukr', 'Ukraine', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'are', 'United Arab Emirates', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'gbr', 'United Kingdom', 1, 1);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'tza', 'United Republic Of Tanzania', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'usa', 'United States', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'umi', 'United States Minor Outlying Islands', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'ury', 'Uruguay', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'uzb', 'Uzbekistan', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'vut', 'Vanuatu', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'vat', 'Vatican City State', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'ven', 'Venezuela', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'vnm', 'Vietnam', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'wlf', 'Wallis and Futuna', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'esh', 'Western Sahara', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'yem', 'Yemen', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'zmb', 'Zambia', 0, null);
			insert into country (version, iso_code, name, we_ship_to, importance_order) values (0, 'zwe', 'Zimbabwe', 0, null);
		""")
	}
}
