
package com.adyen.services.payment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PaymentPortType", targetNamespace = "http://payment.services.adyen.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PaymentPortType {


    /**
     * 
     * @param paymentRequest
     * @return
     *     returns com.adyen.services.payment.PaymentResult
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "paymentResult", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "authorise", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.Authorise")
    @ResponseWrapper(localName = "authoriseResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.AuthoriseResponse")
    public PaymentResult authorise(
        @WebParam(name = "paymentRequest", targetNamespace = "http://payment.services.adyen.com")
        PaymentRequest paymentRequest)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param paymentRequest3D
     * @return
     *     returns com.adyen.services.payment.PaymentResult
     * @throws ServiceException_Exception
     */
    @WebMethod(operationName = "authorise3d")
    @WebResult(name = "paymentResult", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "authorise3d", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.Authorise3D")
    @ResponseWrapper(localName = "authorise3dResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.Authorise3DResponse")
    public PaymentResult authorise3D(
        @WebParam(name = "paymentRequest3d", targetNamespace = "http://payment.services.adyen.com")
        PaymentRequest3D paymentRequest3D)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param modificationRequest
     * @return
     *     returns com.adyen.services.payment.ModificationResult
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "authoriseReferralResult", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "authoriseReferral", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.AuthoriseReferral")
    @ResponseWrapper(localName = "authoriseReferralResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.AuthoriseReferralResponse")
    public ModificationResult authoriseReferral(
        @WebParam(name = "modificationRequest", targetNamespace = "http://payment.services.adyen.com")
        ModificationRequest modificationRequest)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.adyen.services.payment.BalanceCheckResult
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "balanceCheck", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.BalanceCheck")
    @ResponseWrapper(localName = "balanceCheckResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.BalanceCheckResponse")
    public BalanceCheckResult balanceCheck(
        @WebParam(name = "request", targetNamespace = "http://payment.services.adyen.com")
        BalanceCheckRequest request)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param modificationRequest
     * @return
     *     returns com.adyen.services.payment.ModificationResult
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "cancelResult", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "cancel", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.Cancel")
    @ResponseWrapper(localName = "cancelResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.CancelResponse")
    public ModificationResult cancel(
        @WebParam(name = "modificationRequest", targetNamespace = "http://payment.services.adyen.com")
        ModificationRequest modificationRequest)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param modificationRequest
     * @return
     *     returns com.adyen.services.payment.ModificationResult
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "cancelOrRefundResult", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "cancelOrRefund", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.CancelOrRefund")
    @ResponseWrapper(localName = "cancelOrRefundResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.CancelOrRefundResponse")
    public ModificationResult cancelOrRefund(
        @WebParam(name = "modificationRequest", targetNamespace = "http://payment.services.adyen.com")
        ModificationRequest modificationRequest)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param modificationRequest
     * @return
     *     returns com.adyen.services.payment.ModificationResult
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "captureResult", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "capture", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.Capture")
    @ResponseWrapper(localName = "captureResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.CaptureResponse")
    public ModificationResult capture(
        @WebParam(name = "modificationRequest", targetNamespace = "http://payment.services.adyen.com")
        ModificationRequest modificationRequest)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param paymentRequest
     * @return
     *     returns com.adyen.services.payment.PaymentResult
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "paymentResult", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "checkFraud", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.CheckFraud")
    @ResponseWrapper(localName = "checkFraudResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.CheckFraudResponse")
    public PaymentResult checkFraud(
        @WebParam(name = "paymentRequest", targetNamespace = "http://payment.services.adyen.com")
        PaymentRequest paymentRequest)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.adyen.services.payment.DirectDebitResponse
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "directdebit", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.Directdebit")
    @ResponseWrapper(localName = "directdebitResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.DirectDebitResponse")
    public DirectDebitResponse directdebit(
        @WebParam(name = "request", targetNamespace = "http://payment.services.adyen.com")
        DirectDebitRequest request)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.adyen.services.payment.FundTransferResult
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "fundTransfer", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.FundTransfer")
    @ResponseWrapper(localName = "fundTransferResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.FundTransferResponse")
    public FundTransferResult fundTransfer(
        @WebParam(name = "request", targetNamespace = "http://payment.services.adyen.com")
        FundTransferRequest request)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param modificationRequest
     * @return
     *     returns com.adyen.services.payment.ModificationResult
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "refundResult", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "refund", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.Refund")
    @ResponseWrapper(localName = "refundResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.RefundResponse")
    public ModificationResult refund(
        @WebParam(name = "modificationRequest", targetNamespace = "http://payment.services.adyen.com")
        ModificationRequest modificationRequest)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.adyen.services.payment.PaymentResult
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "refundWithData", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.RefundWithData")
    @ResponseWrapper(localName = "refundWithDataResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.RefundWithDataResponse")
    public PaymentResult refundWithData(
        @WebParam(name = "request", targetNamespace = "http://payment.services.adyen.com")
        PaymentRequest request)
        throws ServiceException_Exception
    ;

}
