
package com.adyen.services.payment;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Payment", targetNamespace = "http://payment.services.adyen.com", wsdlLocation = "https://pal-live.adyen.com/pal/Payment.wsdl")
public class Payment
    extends Service
{

    private final static URL PAYMENT_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.adyen.services.payment.Payment.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.adyen.services.payment.Payment.class.getResource(".");
            url = new URL(baseUrl, "https://pal-live.adyen.com/pal/Payment.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://pal-live.adyen.com/pal/Payment.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PAYMENT_WSDL_LOCATION = url;
    }

    public Payment(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Payment() {
        super(PAYMENT_WSDL_LOCATION, new QName("http://payment.services.adyen.com", "Payment"));
    }

    /**
     * 
     * @return
     *     returns PaymentPortType
     */
    @WebEndpoint(name = "PaymentHttpPort")
    public PaymentPortType getPaymentHttpPort() {
        return super.getPort(new QName("http://payment.services.adyen.com", "PaymentHttpPort"), PaymentPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentPortType
     */
    @WebEndpoint(name = "PaymentHttpPort")
    public PaymentPortType getPaymentHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://payment.services.adyen.com", "PaymentHttpPort"), PaymentPortType.class, features);
    }

}
